version: '3.7'

networks:
  nlw17-server:
    name: nlw17-server
    driver: bridge

volumes:
  postgres: { }
  pgadmin: { }

services:
  pg:
    container_name: nlw17-pg
    image: bitnami/postgresql:13.16.0
    networks:
      - nlw17-server
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inorbit
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    container_name: nlw17-pg-admin
    image: dpage/pgadmin4
    networks:
      - nlw17-server
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=nlw17@nlw17.com  
      - PGADMIN_DEFAULT_PASSWORD=nlw17


